version: "3.8"
services:
  vouchergovgr-mysql:
    build: ./mysql
    image: vouchergovgr-mysql:latest
    container_name: vouchergovgr-mysql
    ports: 
      - "3306:3306"
    volumes:
      - vouchergovgr-varlibmysql:/var/lib/mysql
      #- ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z
  vouchergovgr-php:
      build: ./php
      image: vouchergovgr-php:latest
      container_name: vouchergovgr-php
      ports: 
        - "8080:80"
      volumes:
        - .:/var/www/app:Z
      environment:
        DB_HOST: vouchergovgr-mysql
      links:
        - vouchergovgr-mysql
